#
# Continuous integration settings for Travis CI
#
dist: trusty
sudo: false
branches:
  only:
    - master

# Play Framework 2.x only works with Java SDK8
language: scala
scala:
  - 2.11.7
jdk:
  - oraclejdk8

# Build Stages Order
stages:
  - check styles
  - unit tests

# The following settings allow us to run concurrent tests using the scripts in the "bin" folder.
# It also caches things related to SBT. If caching errors occur, please clear the cache on the
# Travis CI website.
jobs:
  include:
    # This stage makes sure that our code styles are the same.
    - stage: check styles
      before_script:
        - chmod +x bin/runFormatter
      script:
        - bin/runFormatter
    - stage: check styles
      before_script:
        - chmod +x bin/runLicensePlugin
      script:
        - bin/runLicensePlugin
    # This stage runs the Scala + JUnit tests.
    - stage: unit tests
      before_script:
        - cp test/lib/*.jar custom_lib
        - chmod +x bin/runUnitTests
      script:
        - bin/runUnitTests
cache:
  directories:
    - "$HOME/.ivy2/cache"
before_cache:
  # Ensure changes to the cache aren't persisted (From Play Framework's .travis.yml)
  - rm -rf $HOME/.ivy2/cache/com.typesafe.play/*
  - rm -rf $HOME/.ivy2/cache/scala_*/sbt_*/com.typesafe.play/*
  # Delete all ivydata files since ivy touches them on each build (From Play Framework's .travis.yml)
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print0 | xargs -n10 -0 rm